### ISSUE TITLE
Dragging from right to left

### ISSUE THREAD

**Issue by igorapa** [nitinhayaran/jRange#10]
Hello!

When l drag the two bullets left an they are on top of the other, l can drag back to right.
But when I drag them to the right, leaving one over the other again, l can not go back to left.
Test in firefox and chrome

See the gif:
![gif-bug](https://cloud.githubusercontent.com/assets/4086866/5740067/4bc27586-9be7-11e4-8ccd-e03a2bb5ef28.gif)

**Comment by nitinhayaran** [comment]
Ye this indeed is an issue. Will fix this very soon.
