### ISSUE TITLE
New color Theme !!

### ISSUE THREAD

**Issue by codexploder** [nitinhayaran/jRange#13]
Trying to add new theme in jquery.range.less. It didn't work.
what steps should i be following ?

**Comment by nitinhayaran** [comment]
You can simply add a new theme in jquery.range.less file. For an example you can see existing .theme-blue and .theme-green

**Comment by codexploder** [comment]
Thanks for reply.
I did figure it out. But need to edit css file as well along with
jquery.range.less

Thanks again.

**Comment by nitinhayaran** [comment]
Well less is CSS pre-processor, it needs to be compiled to .css file. You won't have to do it manually.
to know more checkout http://lesscss.org/

**Comment by codexploder** [comment]
Thanks Nitin, 
LESS is very interesting. I will try to use it in future. 

I want to disable slider so that it cannot be moved around with isRange: true.
if you can please help.

**Comment by nitinhayaran** [comment]
So you'd like to disable to slider, that means it will be only for representational purposes. User won't be able to interact with it. 

Currently this feature is not there, I'd add it in future releases.

**Comment by nitinhayaran** [comment]
Just to let you know I have added functionality to disable the slider.
