### ISSUE TITLE
Formatting labels for high and low pointer labels

### ISSUE THREAD

**Issue by andyweiss1982** [nitinhayaran/jRange#16]
Hello, great project!  Could you please elaborate one the syntax for displaying different labels for the high and low pointers?  

I see the documentation here but am struggling with the proper way to form my function.

Function : format(value, pointer) 
return : string label for a given value and pointer. 
pointer could be 'low'/'high' if isRange is true, else undefined 

Many thanks

**Comment by nitinhayaran** [comment]
I haven't tested it but I think something like this should work 

```javascript
format(value, pointer){
    if(value==='low'){
        return 'from ' + value;
    } else {
        return 'to ' + value;
    }
}

**Comment by andyweiss1982** [comment]
Perfect, thank you

**Comment by daddyschmack** [comment]
Hi Nitin,
I'm trying to wrap my head around this.  I want to format my label values as dollars.  So I'm trying this:

...
  to: 100000000,
  format:function(value, type){
                console.log(value);
                return type === 'low' ? formatDollars(value) + ' first slider' : value + ' second slider';
            },
 step: 1,
..
but it's not working..
