### ISSUE TITLE
Feature request: snap slider to step values

### ISSUE THREAD

**Issue by opatut** [nitinhayaran/jRange#18]
Make it an option (e.g. `snap`) that if enabled moves the slider to the center position of the step when released. This is important when using the plugin for small ranges, such as 0...5 with step 1.

**Comment by marcelpanse** [comment]
+1. This is the reason I can't use this.

**Comment by nitinhayaran** [comment]
Hi,

I have just added this ability in https://github.com/nitinhayaran/jRange/tree/dev. I have done some initial testing, could you guys please also test and let me know if it is working fine. 

After testing i'll merge this into master.

**Comment by nitinhayaran** [comment]
https://github.com/nitinhayaran/jRange/pull/48 closes this
