### ISSUE TITLE
Formatting Label as Currency

### ISSUE THREAD

**Issue by daddyschmack** [nitinhayaran/jRange#21]
Nitin,

I was looking at the closed issues, and I found one that i think relates to me.. but I was unable to wrap my head around it.

https://github.com/nitinhayaran/jRange/issues/16

So I added the below comment and was hoping to bring it to your attention.

Thanks,

John

-----------------

Hi Nitin,
I'm trying to wrap my head around this. I want to format my label values as dollars. So I'm trying this:

...
to: 100000000,
format:function(value, type){
console.log(value);
return type === 'low' ? formatDollars(value) + ' first slider' : value + ' second slider';
},
step: 1,
..
but it's not working..

**Comment by nitinhayaran** [comment]
Do you want something like this?

http://jsfiddle.net/4qjzyk3s/

**Comment by daddyschmack** [comment]
yep, pretty much.. :-)   
Thank you!!  Where do I donate?
