### ISSUE TITLE
help wanted: Dinamicaly change 'To' parameter:

### ISSUE THREAD

**Issue by dimer28** [nitinhayaran/jRange#23]
Hi nitinhayaran,

Thank you for the great script. I am adopting it for my website, however I run into issue.
Please can you help to figure out how I can dynamically change the TO parameter of the slider?

for example when page is loaded the slider is from 0 to 150.
but after user make his selections then the slider will change to 0 to 200 or 0 to 100 depends on the selection.

I hope you can reply soon, Thank you once again.

Dmitri

**Comment by nitinhayaran** [comment]
I am afraid there is no direct way to achieve this, however you can hack around your way to do this. 

Have a look at this http://jsfiddle.net/nitinh/v1c2hvnj/

**Comment by dimer28** [comment]
It is perfect solution - exactly what I needed, thank you!

**Comment by Hamer-2014** [comment]
You solution solve my problem,Thank You
