### ISSUE TITLE
onstatechange only works on the first state change

### ISSUE THREAD

**Issue by BBUEHLER** [nitinhayaran/jRange#24]
onstatechange only works on the first state change. All subsequent changes to the slider are ignored. Maybe I am doing something wrong. Below is the code I am trying to use. Thanks in advanced for any help with this.

$('.single-slider').jRange({
		from: 1,
		to: 28,
		step: 1,
		format: '%s',
		width: 375,
		showLabels: false,
		showScale: false,
		onstatechange: function(){

       		if (val = 1) {
				
			}
			if (val = 2) {
				
			.....	
			}
			if (val = 3) {
				
			.....	
			}
			if (val = 4) {
				
			.....	
			}
    	},
	});

**Comment by nitinhayaran** [comment]
I don't think it is the case, please see the this http://jsfiddle.net/nitinh/dj8r4q2k/

Looks like you have typo in onstatechange function, there is a parameter missing.

**Comment by BBUEHLER** [comment]
You are totally right! Thank you for the help. I got it working. I'm still in school learning this stuff. This is an awesome program.
