### ISSUE TITLE
Setting values

### ISSUE THREAD

**Issue by baroale** [nitinhayaran/jRange#25]
Hello, I am writing because I am using your plug in for a project I am currently working on. The issue is that I needed a button to clear the slider (either destroying it or setting it to zero).
What I did was:

`var selector = $('#PriceRangeSelector');`
`selector.jRange('disable');`
`selector.data("plugin_jRange").setValue("0,0");`
`selector.jRange('enable');`

Is there any other way to do it? If so, could it be added to the documentation?

**Comment by nitinhayaran** [comment]
You can do it something like 
```selector.jRange('setValue', '0,0');```

I'll write that in documentation. Also it'd even better to have PR. :)

**Comment by baroale** [comment]
Thank you. Sure, I can do a PR in the WE.
