### ISSUE TITLE
Changing the slider's value by code

### ISSUE THREAD

**Issue by viranianish** [nitinhayaran/jRange#30]
I am trying to change the value of the slider by code, but it does not change and even it does not show any error.

**Comment by nitinhayaran** [comment]
A jsfiddle or some public link would be required to help you further.

**Comment by viranianish** [comment]
Dear Sir,
I have further analyzed that once the slider has been rendered, even if we change the attributes of the slider (like value or scale), it gets reflected in the attribute variables but it does not affect the slider.
It would be great if you help me with some trick to get the changes reflected in the slider.

Or could you please help me with setting the maximum value in the slider once it has been rendered.

Any one of the above would be helpful to me.

Thanks in advance..

**Comment by nitinhayaran** [comment]
If you need to update the value of the slider then your should see https://github.com/nitinhayaran/jRange/issues/6 and https://github.com/nitinhayaran/jRange/issues/25

However if you want to update range all together, you could simply re-render complete range slider.

**Comment by viranianish** [comment]
Sir,
Thank You, Now I am able to change the value of the slider,
But as I am new to jquery, I am not able to re-render the slider and I even do not find anything like this in the documentation,
Kindly help me with the re-rendering,
Thanks in advance..
