### ISSUE TITLE
how to refresh

### ISSUE THREAD

**Issue by lucasroselli** [nitinhayaran/jRange#33]
I looking for a way to refresh the slider, is it possible ?

Scenario: I updating the value o input by javascript but the JRange don't listem to this change

**Comment by nitinhayaran** [comment]
this will work for you, 
https://github.com/nitinhayaran/jRange/issues/5

Also could you please send me a pull request by writing the same in documentation. A lot of people are getting the same issue.

**Comment by lucasroselli** [comment]
Thank you Nitin Hayaran!! That was exactly what I was needing
Sorry, I don't know how to use Git Hub yet to send this pull request.
