### ISSUE TITLE
How can i get value of jRange by javascript or jquery?

### ISSUE THREAD

**Issue by khanhgooner** [nitinhayaran/jRange#34]
Hi

I use javascript and jquery event to get the value of jRange but it can not to do that?

My ex: 

$('#price-range').bind('input', function() { 
  alert($(this).val()) // get the current value of the input field.
});

$('#price-range').keyup(function() {
    alert($(this).val()) // get the current value of the input field.
});

$(document).ready(function(){
    $("#price-range").change(function(){
        alert("The text has been changed.");
    });
});

Thanks

**Comment by nitinhayaran** [comment]
Either do this
```
$('.range-slider').jRange({
    from: 0,
    to: 100,
    step: 1,
    scale: [0,25,50,75,100],
    format: '%s',
    width: 300,
    showLabels: true,
    isRange : true
   onstatechange: function(value){console.log(value);}
});
```

Or whenever you want value you can simply get the value as ```$('.range-slider').val();```

**Comment by khanhgooner** [comment]
Hi thank you it works fine but i want to use javascript event onchange to get the value. How can i use javascript to get value change when the input jRange change.

**Comment by khanhgooner** [comment]
hi sorry, it's working right now, thank so much.

**Comment by jai106** [comment]
$('.range-slider').jRange({
    from: 0,
    to: 100,
    step: 1,
    scale: [0,25,50,75,100],
    format: '%s',
    width: 300,
    showLabels: true,
    isRange : true,
    onstatechange: function(value){console.log(value);}
});
$('.range-slider').on('change', function() {

    console.log(this.value);

});

i use this its showing jRange is not a function

**Comment by MamoonPAK** [comment]
$('.simple-slider').jRange({
        from: 1,
        to: 4,
        step: 1,
       scale: ['A','B','C','D'],       
        format: '%s',
        width: 300,
        showLabels: false,
        snap: true,
        onbarclicked: function () {
            getSliderValue()
        },
        ondragend: function () {
            getSliderValue()
        }
    });

function getSliderValue()
{
    var SliderVAL = $('.simple-slider').jRange('getValue');
    return SliderVAL;
}

We can use any event instead of 'onbarclicked' or 'ondragend' as per our requirement.

**Comment by patmccormick** [comment]
None of these answers explain how to get the high and low values for a jrange slider.
