### ISSUE TITLE
.indexOf not defined

### ISSUE THREAD

**Issue by izanev** [nitinhayaran/jRange#53]
Line 295 makes me a problem when I try to initialize a single slider:

`return ((this.options.value + this.options.from + this.options.to).indexOf(".")===-1) ? false : true;
`
I passed all numbers for from and to and it thinks the value is a number, so "indexOf" is not available. I have to convert to string the values and then it works:

`return (("" + (this.options.value + this.options.from + this.options.to)).indexOf(".")===-1) ? false : true;
`

**Comment by riku25591** [comment]
I had the same issue and your fix is working fine, good job

**Comment by rysinal** [comment]
jquery.range.js:295 Uncaught TypeError: ((this.options.value + this.options.from) + this.options.to).indexOf is not a function
I had the same issue...

**Comment by Donzella** [comment]
Yup, I had the same issue. izanev's fix did the trick. Thanks.

**Comment by KALEFA** [comment]
Thanks!! That worked for me too!

**Comment by zouhuigang** [comment]
thank you!!

**Comment by siddhuphp** [comment]
Thank you!! Saved my time

**Comment by LiuhaoWang** [comment]
Thanks!!
