### ISSUE TITLE
the problem of setting default value

### ISSUE THREAD

**Issue by weub** [nitinhayaran/jRange#61]
i found the offical method to set default value have a problem. when you call the `setValue`, you will have a error in the method `isDecimal`. the original method body is `return ((this.options.value + this.options.from + this.options.to).indexOf(".")===-1) ? false : true;`
`this.options.value + this.options.from + this.options.to` plus together will be the int type value, it can't call the string type method `indexOf`, so, i try to have a modify with this method body.
`return (((this.options.value + this.options.from + this.options.to)+"").indexOf(".")===-1) ? false : true;`

**Comment by sergeport** [comment]
What is the reason of using concatenation with string against of using String(val) or val.toString()? Every object has toString() method...
