### ISSUE TITLE
How to change array of range {7, 15, 30, 45, 60}

### ISSUE THREAD

**Issue by Gajendrasinh** [nitinhayaran/jRange#8]
Hi i want to use jRange : jQuery Range Selector Plugin with diffrent interval

$(document).ready(function() {
$('.single-slider').jRange({
from: 7,
to: 60,
step: 1,
// scale: [0, 50, 100,150, 200, 250, 300, 350, 400, 450 ,500],
scale: [7, 15, 30, 45, 60],
// format: '%s',
width: 380,
showLabels: true,
});

});

when i select 7-15 interval i got 20 in between this interval how to change this issue can u help me

**Comment by nitinhayaran** [comment]
scale is just for representational purpose, it should be equally distributed. so for current case you could either have [7,  31.5, 60] or [7, 25, 42, 60]. 
~ these are just rounded values.

**Comment by Gajendrasinh** [comment]
as per my project need i not need to rounded values so can any other
solution for as par my choice

**Comment by nitinhayaran** [comment]
No I am afraid not. This plugin works only when scale is uniformly distributed.
